#!/bin/bash
#
# Install Nexus settings for Maven
# Usage: ./install-nexus-settings.sh [nexus-url]
#

set -e

NEXUS_URL="${1:-http://astronauta.biruta.net:31000/repository/maven-public}"
M2_DIR="$HOME/.m2"
SETTINGS_FILE="$M2_DIR/settings.xml"

echo "Installing Nexus Maven settings..."
echo "Nexus URL: $NEXUS_URL"
echo "Settings file: $SETTINGS_FILE"

# Create .m2 directory if it doesn't exist
mkdir -p "$M2_DIR"

# Backup existing settings.xml if it exists
if [ -f "$SETTINGS_FILE" ]; then
    BACKUP_FILE="$SETTINGS_FILE.backup.$(date +%Y%m%d-%H%M%S)"
    echo "Backing up existing settings.xml to: $BACKUP_FILE"
    cp "$SETTINGS_FILE" "$BACKUP_FILE"
fi

# Create new settings.xml
cat > "$SETTINGS_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <!-- 
    Nexus Repository Mirror Configuration
    Generated by install-nexus-settings.sh
    $(date)
    -->

    <mirrors>
        <mirror>
            <id>nexus</id>
            <name>Nexus Repository Mirror</name>
            <url>$NEXUS_URL</url>
            <mirrorOf>*</mirrorOf>
        </mirror>
    </mirrors>

    <!-- 
    Uncomment and configure if authentication is required:
    
    <servers>
        <server>
            <id>nexus</id>
            <username>your-username</username>
            <password>your-password</password>
        </server>
    </servers>
    -->

</settings>
EOF

echo ""
echo "✓ Nexus settings installed successfully!"
echo ""
echo "Settings file created at: $SETTINGS_FILE"
echo ""
echo "To test:"
echo "  mvn clean compile"
echo ""
echo "To add authentication (if required):"
echo "  Edit $SETTINGS_FILE and uncomment the <servers> section"
echo ""
echo "To disable Nexus temporarily:"
echo "  mv $SETTINGS_FILE ${SETTINGS_FILE}.disabled"
echo ""
