name: Java CI with Maven

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      java-version: "25"
      jdk-distribution: "semeru"
      log-artifact-suffix: "ci-build"
      maven-goals: "clean verify"
      generate-jacoco-badge: true
      codecov-coverage: true
      codecov-test-results: true
      upload-jacoco: true
      comment-pr-coverage: true
